<?php
$sqlitename = 'phpdata.db';
$db = new SQLite3($sqlitename);
$db->query("CREATE TABLE IF NOT EXISTS OPTIONS(
ID INTEGER PRIMARY KEY AUTOINCREMENT,
OPTION_NAME TEXT NOT NULL,
OPTION_VALUE TEXT NOT NULL);");
$db->query("INSERT INTO OPTIONS (OPTION_NAME , OPTION_VALUE) VALUES ('COLOR' , 'RED'),('BACKGROUND' , 'WHITE');");
$db->query("INSERT INTO OPTIONS (OPTION_NAME , OPTION_VALUE) VALUES ('FONT-SIZE' , '14')");